// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using e_descarte_api.Data;

namespace e_descarte_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200907042617_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("e_descarte_api.Models.PontoDescarte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("fone")
                        .HasColumnType("text");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("pontodescarte");

                    b.HasData(
                        new
                        {
                            id = 1,
                            fone = "(48) 3445-8811",
                            latitude = -28.686900999999999,
                            longitude = -49.384303000000003,
                            nome = "FAMCRI"
                        },
                        new
                        {
                            id = 2,
                            fone = "(48) 3431-3700",
                            latitude = -28.681298000000002,
                            longitude = -49.3748468,
                            nome = "Faculdades ESUCRI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
